---
- name: PostgreSQL Backup & Restore with Test Data
  hosts: all
  become: true
  vars:
    master_address: "192.168.57.11"
    master_port: "5432"
    barman_address: "192.168.57.13"
    backup_user: "backup_user"
    backup_password: "Qwerty123"
    backup_dir: "/var/lib/postgresql/backups"
    test_db: "otus_test"
    test_table: "test"
    postgres_data_dir: "/var/lib/postgresql/14/main"
    postgres_version: "14"

  tasks:
    # 1. Подготовка тестовых данных на master (node1)
    - name: Create test database
      postgresql_db:
        name: "{{ test_db }}"
        state: present
      when: ansible_hostname == 'node1'
      become_user: postgres

    - name: Create test table with primary key
      postgresql_query:
        db: "{{ test_db }}"
        query: |
          CREATE TABLE IF NOT EXISTS {{ test_table }} (
            id SERIAL PRIMARY KEY,
            name VARCHAR(30)
          )
      when: ansible_hostname == 'node1'
      become_user: postgres

    - name: Insert test data
      postgresql_query:
        db: "{{ test_db }}"
        query: |
          INSERT INTO {{ test_table }} (id, name) VALUES
          (1, 'Jack'),
          (2, 'Alice'),
          (3, 'Bob')
          ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
      when: ansible_hostname == 'node1'
      become_user: postgres

    # 2. Выполнение бэкапа на barman
    - name: Ensure backup directory does not exist
      file:
        path: "{{ backup_dir }}/pg_backup_{{ ansible_date_time.date }}"
        state: absent
      when: ansible_hostname == 'barman'

    - name: Perform base backup
      command: >
        pg_basebackup -h {{ master_address }} -p {{ master_port }} -U {{ backup_user }}
        -D {{ backup_dir }}/pg_backup_{{ ansible_date_time.date }}
        -Ft -z -Xs -P -v
      environment:
        PGPASSWORD: "{{ backup_password }}"
      when: ansible_hostname == 'barman'
      register: backup_result
      retries: 3
      delay: 10

    - name: Show backup result
      debug:
        msg: "{{ backup_result }}"
      when: ansible_hostname == 'barman'

    - name: List backup directory to check for the backup file
      command: ls -l {{ backup_dir }}/pg_backup_{{ ansible_date_time.date }}
      when: ansible_hostname == 'barman'
      register: backup_directory_contents
      failed_when: false

    - name: Show backup directory contents
      debug:
        msg: "{{ backup_directory_contents.stdout }}"
      when: ansible_hostname == 'barman'
